services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    container_name: rag-backend-container

    ports:
      - "8000:8000"

    environment:
      OLLAMA_HOST: http://host.docker.internal:11434

    volumes:
      - ./qdrant_store:/app/qdrant_store

    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: rag-frontend-container

    ports:
      - "5173:80"

    depends_on:
      - backend