[project]
name = "generative-ai-learning"
version = "0.1.0"
description = "this project is for learning basic RAG"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "docx2txt>=0.9",
    "ipykernel>=7.3.0",
    "jq>=1.12.0",
    "langchain>=1.3.18",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.1",
    "langchain-ollama>=1.1.0",
    "langfuse>=4.15.1",
    "ollama>=0.6.2",
    "pymupdf>=1.28.2",
    "pypdf>=6.16.2",
    "python-dotenv>=1.2.3",
    "qdrant-client>=1.19.0",
    "requests>=2.34.2",
    "sentence-transformers>=6.0.1",
] 
