import ollama #importing the Ollama Python SDK.This allows Python to communicate with our local Ollama server.
'''SDK = Software Development Kit

Instead of manually creating an HTTP request, we can do:

ollama.chat(...)

The SDK handles communication with Ollama for you.'''


#The messages list is the conversation history being sent to the model.
messages = [
    {
        "role": "system",
        "content": "You are a kind and helpful assistant."
    }
]

while True:

    user_message = input("You: ")

    if user_message.lower() == "exit":
        break

#user question is stored in the messages list, which is sent to the model.
    messages.append({
        "role": "user",
        "content": user_message
    })

    response = ollama.chat(   #communicates with your local Ollama server.
        model="llama3.2",
        messages=messages
    )

    assistant_message = response["message"]["content"] #This extracts the actual text generated by Llama.

    print("Assistant:", assistant_message)

#the assistant's answer is also stored.
    messages.append({
        "role": "assistant",
        "content": assistant_message 
    })

'''Python
   │
   │ ollama.chat()
   ↓
Ollama
   │
   │ model = llama3.2
   ↓
Llama 3.2
   │
   │ generates answer
   ↓
Ollama
   │
   ↓
Python''' 